"use client";
import {useState,useEffect,useRef} from 'react';
import MessageForm from './message-form';
import {projects} from '@/lib/projects';
import {ArrowUpRight,ArrowLeft,X,Frame,Monitor,FolderOpen,StickyNote} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const entries=[{id:'about',label:'关于我',en:'ABOUT ME',Icon:Frame},{id:'works',label:'设计作品',en:'SELECTED WORK',Icon:Monitor},{id:'life',label:'设计之外',en:'BEYOND DESIGN',Icon:FolderOpen},{id:'message',label:'给我留言',en:'LEAVE A NOTE',Icon:StickyNote}];
export default function Home(){const[panel,setPanel]=useState<string|null>(null);const[hover,setHover]=useState<string|null>(null);const active=entries.find(e=>e.id===panel);const opener=useRef<HTMLElement|null>(null);
function openPanel(id:string){opener.current=document.activeElement as HTMLElement;setPanel(id)}
useEffect(()=>{if(location.hash==='#works')setPanel('works')},[]);
return <main className="studio"><div className="scene-art"><picture><source media="(max-width:700px)" srcSet="./assets/studio-mobile.webp"/><img className="scene-image" src="./assets/studio-desktop.webp" alt="落日暖光中的个人设计工作室，桌上有相框、电脑和文件盒，墙上贴着彩色便签" fetchPriority="high"/></picture>{entries.map((e,i)=><button key={e.id} className={`hotspot spot-${e.id} ${hover===e.id?'is-active':''}`} aria-label={`打开${e.label}`} onMouseEnter={()=>setHover(e.id)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(e.id)} onBlur={()=>setHover(null)} onClick={()=>openPanel(e.id)}><span className="object-glow"/><span className="hotspot-label"><small>0{i+1}</small>{e.label}<ArrowUpRight size={13}/></span><span className="hotspot-dot"/></button>)}</div><div className="scene-shade"/>
<header className="masthead"><a href="./" className="wordmark">Winnie<span>杨雯茹 / DESIGNER</span></a><span className="header-note"><i/>欢迎来到我的小小世界</span></header><section className="introduction"><p className="eyebrow">A LITTLE SPACE FOR BIG IDEAS</p><h1>用视觉串联想法，<br/>让好设计被看见、被记住<span>。</span></h1></section>
<footer className="studio-footer"><p className="explore-hint">每件小物，都藏着一个故事</p><nav aria-label="工作室导航">{entries.map((e,i)=><button key={e.id} onClick={()=>openPanel(e.id)} onMouseEnter={()=>setHover(e.id)} onMouseLeave={()=>setHover(null)}><e.Icon size={17} strokeWidth={1.5}/><span>{e.label}</span><small>0{i+1}</small></button>)}</nav><div className="footer-meta"><span>WINNIE’S STUDIO</span><a href="https://winnie-design-studio.yangwenru31.chatgpt.site/admin/messages" className="admin-entry">我的收件箱 ↗</a></div></footer>
<Dialog open={!!panel} onOpenChange={v=>!v&&setPanel(null)}><DialogContent className={`studio-dialog panel-${panel}`} showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();opener.current?.focus()}}><div className="panel-top"><span className="eyebrow">{active?.en}</span><button className="icon-button" aria-label="关闭，返回工作室" onClick={()=>setPanel(null)}><X size={21}/></button></div><DialogTitle className="panel-title">{active?.label}</DialogTitle><DialogDescription className="sr-only">Winnie 的{active?.label}</DialogDescription>
{panel==='about'&&<div className="about-content"><span className="about-monogram about-photo"><img src="./assets/winnie-photo.png" alt="Winnie 抱着小狗的照片" width={1200} height={1600}/></span><div><p className="eyebrow">HELLO, I’M WINNIE</p><h2>杨雯茹 <em>/ Winnie</em></h2><p className="about-line">用视觉串联想法，<br/>让好设计被看见、被记住。</p><div className="disciplines">IP 设计 · UI 设计 · 品牌设计 · 活动运营</div><a className="contact-link" href="mailto:2451433219@qq.com">2451433219@qq.com <ArrowUpRight size={18}/></a><a className="contact-link" href="tel:15279280887">15279280887 <ArrowUpRight size={18}/></a></div></div>}
{panel==='works'&&<div className="folder-grid">{projects.map((p,i)=><a className="folder-card" href={`./#project/${p.id}`} key={p.id}><img src={`./assets/folder-${p.id}.webp`} alt={`${p.category}：${p.title}`}/><div><span>0{i+1} / {p.category}</span><ArrowUpRight size={18}/></div><h3>{p.title}</h3></a>)}</div>}
{panel==='life'&&<div className="quiet-state"><FolderOpen size={38} strokeWidth={1}/><h2>在设计之外，收集灵感。</h2><p>生活中的小小发现，正在整理中。</p></div>}
{panel==='message'&&<MessageForm/>}
<button className="back-link" onClick={()=>setPanel(null)}><ArrowLeft size={15}/>返回工作室</button></DialogContent></Dialog></main>}
