"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Plus,Minus,Maximize2,ArrowUp} from 'lucide-react';
import PrototypeDemo from './prototype-demo';
import type {Project} from '@/lib/projects';
export default function Reader({project,next}:{project:Project;next:Project}){
 const[zoom,setZoom]=useState(100);const[progress,setProgress]=useState(0);const[top,setTop]=useState(false);const scroller=useRef<HTMLDivElement>(null);const[errors,setErrors]=useState<Record<string,boolean>>({});const[retries,setRetries]=useState<Record<string,number>>({});
 useEffect(()=>{const read=()=>{const h=document.documentElement.scrollHeight-innerHeight;setProgress(h>0?scrollY/h*100:0);setTop(scrollY>600)};addEventListener('scroll',read,{passive:true});addEventListener('resize',read);read();return()=>{removeEventListener('scroll',read);removeEventListener('resize',read)}},[]);
 return <main className="reader"><header className="reader-header"><a href="./#works" className="reader-back"><ArrowLeft size={17}/><span>所有作品</span></a><div className="reader-name"><span>{project.category}</span><strong>{project.title}</strong></div><a href="./" className="reader-home">Winnie<span>’s studio ↗</span></a><div className="reading-progress" style={{width:`${progress}%`,background:project.color}}/></header><div className={`reader-layout ${project.prototypeUrl?'with-prototype':''}`}><section className="project-intro"><p className="eyebrow">SELECTED WORK / {project.en}</p><h1>{project.title}<span style={{color:project.color}}>↗</span></h1><p>{project.summary}</p><div><span>{project.category}</span><span>杨雯茹 / Winnie</span></div></section>{project.prototypeUrl&&<PrototypeDemo url={project.prototypeUrl}/>}<div className="project-document">
 <div className="reader-toolbar"><span>项目全貌<span className="reader-tip"> · 可放大查看细节</span></span><div><button aria-label="缩小作品" disabled={zoom<=75} onClick={()=>setZoom(z=>Math.max(75,z-25))}><Minus size={16}/></button><output aria-label="缩放比例">{zoom}%</output><button aria-label="放大作品" disabled={zoom>=200} onClick={()=>setZoom(z=>Math.min(200,z+25))}><Plus size={16}/></button><button aria-label="适应屏幕宽度" onClick={()=>{setZoom(100);if(scroller.current)scroller.current.scrollLeft=0}}><Maximize2 size={16}/></button></div></div>
 <div className="project-canvas" ref={scroller}><div className="project-pages" style={{width:`${zoom}%`}}>{project.images.map((im,i)=><div className="project-image" key={im.src} style={{aspectRatio:`${im.width}/${im.height}`}}>{errors[im.src]?<div className="image-error"><p>这一页暂时未能加载</p><button onClick={()=>{setErrors(e=>({...e,[im.src]:false}));setRetries(r=>({...r,[im.src]:(r[im.src]||0)+1}))}}>重新加载第 {i+1} 部分</button></div>:<img src={im.src+(retries[im.src]?`?retry=${retries[im.src]}`:'')} alt={`${project.title}项目展示，第 ${i+1} 部分`} width={im.width} height={im.height} loading={i===0?'eager':'lazy'} decoding="async" onError={()=>setErrors(e=>({...e,[im.src]:true}))}/>}</div>)}</div></div>
 <section className="next-project"><p className="eyebrow">THANK YOU FOR EXPLORING</p><h2>下一份想法，继续看看。</h2><a href={`./#project/${next.id}`}><img src={`./assets/folder-${next.id}.webp`} alt=""/><div><span>{next.category}</span><h3>{next.title}</h3></div><ArrowUpRight size={32}/></a><a href="./#works" className="back-link"><ArrowLeft size={15}/>返回全部作品</a></section></div></div>{top&&<button className="scroll-top" aria-label="回到顶部" onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp size={20}/></button>}</main>
}
